#####################################
# Video Reconstructor Configuration #
#####################################

# Input Events Packages <dvs_msgs/EventArray>
dvs_events_topic: "/dvs/events"

# Output Reconstructed Video <sensor_msgs/Image>
reconstructed_video_topic: "/dvs/reconstructed_video"
video_frame_rate: 10 # FPS

# Input / Output Resolution (pixels)
camera_width: 640
camera_height: 480
